framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: medleybox/vault

        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            minio.cache:
                adapter: cache.system
                tags: true
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system