doctrine:
    dbal:
        host: db
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        driver: 'pdo_pgsql'
        server_version: '12'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
