framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    #csrf_protection: true
    #http_method_override: true

    session:
        enabled: false

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        default_options:
            http_version: '2.0'