framework:
    messenger:
        reset_on_message: true
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\ImportJob':  async
            'App\Message\RefreshJob':  async
