framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            # Route your messages to the transports
            'App\Message\ImportJob':  async
