image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

test:run-tests:
  stage: test
  image: ${CI_REGISTRY}/medleybox/php-cli:master
  tags:
    - docker
  before_script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" Dockerfile
    - sed -i "s/:master/:latest/g" Dockerfile
    - composer install -vvv
  script:
    - bin/run-tests

build:vault:
  stage: build
  tags:
    - docker
  before_script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" Dockerfile
    - sed -i "s/:master/:latest/g" Dockerfile
  script:
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      -f Dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:latest

build:messenger:
  needs: ["build:vault"]
  stage: build
  tags:
    - docker
  before_script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" Dockerfile-messenger
    - sed -i "s/:master/:latest/g" Dockerfile-messenger
  script:
    - >
      docker build
      --pull
      --tag ${CI_REGISTRY}/medleybox/messenger:latest
      -f Dockerfile-messenger
      .
    - docker push ${CI_REGISTRY}/medleybox/messenger:latest