version: '3.7'

x-variables: &x-variables
  APP_ENV: dev
  APP_SECRET: c95ab68cbfba3232e79d72ebae567424
  POSTGRES_USER: medleybox
  POSTGRES_PASSWORD: medleybox
  # MINIO_ENDPOINT: ''
  MINIO_ACCESS_KEY: medley
  MINIO_BUCKET: medley
  MINIO_SECRET_KEY: h15QXfIaJVdcTQdqTQm6pYwYjFa7x87TfhF47CPf
  # Test key to be removed in production
  API_GOOGLE: AIzaSyBQpUx4udkIfX130sncXs8tLCdfCDsGYSc

networks:
  medley:
    external: true

services:
  vault:
    image: ghcr.io/medleybox/vault:master
    build:
      context: ./
      dockerfile: Dockerfile
    environment: *x-variables
    networks:
     - medley
    volumes:
      - tmp-data:/var/www/var/tmp
      - ./bin:/var/www/bin
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./phpstan.neon:/var/www/phpstan.neon

  messenger:
    image: ghcr.io/medleybox/messenger:master
    build:
      context: ./
      dockerfile: Dockerfile-messenger
    environment:
      <<: *x-variables
      APP_ENV: prod
    networks:
      - medley
    restart: always
    volumes:
      - tmp-data:/var/www/var/tmp
    depends_on:
      - vault

  websocket:
    image: ghcr.io/medleybox/websocket:master
    build:
      context: ./
      dockerfile: Dockerfile-websocket
    networks:
      - medley
    restart: always
    depends_on:
      - vault

  minio:
    image: minio/minio
    hostname: minio
    environment: *x-variables
    networks:
      - medley
    volumes:
     - minio-data:/data
    ports:
     - "9000:9000"
     - "9001:9001"
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/medley && /usr/bin/docker-entrypoint.sh minio server /data --console-address ':9001'"]

volumes:
  minio-data:
  postgres-data:
  tmp-data:
