version: '3.7'

x-variables: &x-variables
  APP_ENV: dev
  APP_SECRET: c95ab68cbfba3232e79d72ebae567424
  POSTGRES_USER: medleybox
  POSTGRES_PASSWORD: Ze964V98S4w622dzf45WJ37W
  POSTGRES_DB: medleybox_vault
  MINIO_ENDPOINT: http://minio:9000
  MINIO_ACCESS_KEY: medley
  MINIO_BUCKET: medley
  MINIO_SECRET_KEY: h15QXfIaJVdcTQdqTQm6pYwYjFa7x87TfhF47CPf
  # Test key to be removed in production
  API_GOOGLE: AIzaSyBQpUx4udkIfX130sncXs8tLCdfCDsGYSc
  MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages

services:
  vault:
    image: medleybox/vault
    build:
      context: ./
      dockerfile: Dockerfile
    environment: *x-variables
    ports:
     - "8084:80"
    volumes:
      - ./bin:/var/www/bin
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
      - ./var/log:/var/www/var/log

  minio:
    image: minio/minio
    hostname: minio
    environment: *x-variables
    volumes:
     - minio-data:/data
    ports:
     - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/${MINIO_BUCKET} && /usr/bin/minio server /data'`

  db:
    image: postgres:12-alpine
    restart: always
    environment: *x-variables
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  minio-data:
  postgres-data:
