version: '3.7'

x-variables: &x-variables
  APP_ENV: dev
  APP_SECRET: c95ab68cbfba3232e79d72ebae567424
  POSTGRES_USER: medleybox
  POSTGRES_PASSWORD: medleybox
  MINIO_ENDPOINT: 'http://minio:9000'
  MINIO_ROOT_USER: medley
  MINIO_BUCKET: medley
  MINIO_ROOT_PASSWORD: h15QXfIaJVdcTQdqTQm6pYwYjFa7x87TfhF47CPf
  # Test key to be removed in production
  API_GOOGLE: AIzaSyBQpUx4udkIfX130sncXs8tLCdfCDsGYSc
  FPM_WORKERS: 1

networks:
  medley:
    external: true

services:
  vault:
    image: ghcr.io/medleybox/vault:master
    build:
      context: ./
      dockerfile: Dockerfile
    environment: *x-variables
    networks:
     - medley
    volumes:
      - tmp-data:/var/www/var/tmp
      #- vault-vendor:/var/www/vendor
      - ./vendor:/var/www/vendor
      - ~/git/medleybox/vault/src:/var/www/src
      - ~/git/medleybox/vault/phpstan.neon:/var/www/phpstan.neon

  messenger:
    image: ghcr.io/medleybox/messenger:master
    build:
      context: ./
      dockerfile: Dockerfile-messenger
    environment:
      <<: *x-variables
      APP_ENV: prod
    networks:
      - medley
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: always
    volumes:
      - tmp-data:/var/www/var/tmp
    depends_on:
      - vault

  websocket:
    image: ghcr.io/medleybox/websocket-server:master
    networks:
      - medley
    restart: always
    depends_on:
      - vault

  minio:
    image: minio/minio
    hostname: minio
    environment: *x-variables
    ports:
      - "9001:9001"
    networks:
      - medley
    volumes:
     - minio-data:/data
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/medley && /usr/bin/docker-entrypoint.sh minio server /data --console-address ':9001'"]

volumes:
  vault-vendor:
  minio-data:
  postgres-data:
  tmp-data:
