version: '3.7'

x-variables: &x-variables
  APP_ENV: dev
  APP_SECRET: c95ab68cbfba3232e79d72ebae567424
  MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
  POSTGRES_USER: medleybox
  POSTGRES_PASSWORD: medleybox
  POSTGRES_DB: medleybox_vault
  MINIO_ACCESS_KEY: medley
  MINIO_BUCKET: medley
  MINIO_SECRET_KEY: h15QXfIaJVdcTQdqTQm6pYwYjFa7x87TfhF47CPf
  # Test key to be removed in production
  API_GOOGLE: AIzaSyBQpUx4udkIfX130sncXs8tLCdfCDsGYSc

networks:
  medley:
    external: true

services:
  vault:
    image: ghcr.io/medleybox/vault
    build:
      context: ./
      dockerfile: Dockerfile
    environment: *x-variables
    networks:
     - medley
    ports:
     - "8084:80"
    volumes:
      - tmp-data:/var/www/var/tmp
      - ./bin:/var/www/bin
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
      - ./var/log:/var/www/var/log

  messenger:
    image: ghcr.io/medleybox/messenger
    build:
      context: ./
      dockerfile: Dockerfile-messenger
    environment: *x-variables
    networks:
      - medley
    restart: always
    depends_on:
      - vault
      - rabbitmq
    volumes:
      - tmp-data:/var/www/var/tmp
      - ./vendor:/var/www/vendor
    entrypoint: ["bin/console", "messenger:consume", "async", "-vvv"]

  websocket:
    image: ghcr.io/medleybox/vault
    environment:
      <<: *x-variables
      APP_ENV: prod
    networks:
      - medley
    restart: always
    depends_on:
      - vault
    entrypoint: ["bin/console", "app:websocket:start", "-vvv"]

  minio:
    image: minio/minio
    hostname: minio
    environment: *x-variables
    networks:
      - medley
    volumes:
     - minio-data:/data
    ports:
     - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/medley && /usr/bin/minio server /data'

  rabbitmq:
    image: rabbitmq:3
    networks:
      - medley
    expose:
      - "5672"

volumes:
  minio-data:
  postgres-data:
  tmp-data:
