name: PHP Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PHP_VERSION: '8.3'

jobs:
  composer_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - uses: nanasess/setup-php@v4
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nanasess/setup-php@v4
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Run bin/run-tests
        run: bin/run-tests
